# Project Involment

## Agri-analytics Hub

Under the leadership of Dr. Julia Easton and Professor Mark Gibberd, the project seeks to develop a research-based analytics and decision support tool that will allow farmers and their advisors to increase profitability and optimise risk management.

The [Agri-analytics Hub](https://www.foodagility.com/research/agri-analytics-hub) will allow visualisation and analysis of within paddock variability in crop performance and profitability. It also enables users to robustly plan, implement and analyse the outputs of alternative management practices. The Hub will enable users to extend results of experimental outcomes to similar land management units. Collectively this capability will enable farmers to more readily engage with spatial variation in crop performance, to test solutions and then to estimate the likely economic impact of adoption based on results obtained from their own production system.

{{< video https://www.youtube.com/watch?v=J-rITpqp4PE >}}

## On-Farm Water Demand

The [On-Farm Water Demand Project](https://www.foodagility.com/research/on-farm-water-demand) aims to deliver Putting real-time water usage data into the hands of farmers in Manjimup, WA, to enable accurate assessment of the economic value of water for irrigation to agribusinesses and to the community.

## Digital Edge

The [Digital Edge](https://hub.gga.org.au/next-generation-agribusiness-analytics-for-the-eastern-wheatbelt-curtin-university/) project aims to enhance climate resilience in eastern wheat belt of WA by helping farmers and agronomist use farm data to improve profitability and sustainability at paddock, farm, and farm enterprise level.
